DROP SCHEMA IF EXISTS INFY_FACEBOOK_USER;
CREATE SCHEMA INFY_FACEBOOK_USER;
USE INFY_FACEBOOK_USER;

CREATE TABLE USER(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER ENUM('MALE', 'FEMALE', 'OTHERS') NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE USER_PROFILE(
    PROFILE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    PROFILE_PICTURE VARCHAR(255),
    BIO VARCHAR(255),
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    DATE_OF_BIRTH DATE,
    GENDER ENUM('MALE', 'FEMALE', 'OTHERS'),
    PRIVACY_SETTING ENUM('PUBLIC','PRIVATE','ONLY_FRIENDS')
);

DROP SCHEMA IF EXISTS INFY_FACEBOOK_FRIENDREQUEST;
CREATE SCHEMA INFY_FACEBOOK_FRIENDREQUEST;
USE INFY_FACEBOOK_FRIENDREQUEST;

CREATE TABLE FRIEND_REQUEST(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SENT_TO INT,
    SENT_FROM INT,
    REQUEST_STATUS ENUM('PENDING','ACCEPTED','REJECTED')
);

DROP SCHEMA IF EXISTS INFY_FACEBOOK_POSTS;
CREATE SCHEMA INFY_FACEBOOK_POSTS;
USE INFY_FACEBOOK_POSTS;

CREATE TABLE POST(
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    POST_TEXT VARCHAR(255),
    POST_IMAGE VARCHAR(255),
    POST_VIDEO LONGBLOB,
    TIMESTAMP_COLUMN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIVACY_SETTING ENUM('PUBLIC', 'ONLY_FRIENDS')
);

CREATE TABLE LIKES(
    LIKE_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT,
    LIKED_BY INT,
    TIMESTAMP_COLUMN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENT(
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT,
    COMMENT_BY INT,
    COMMENT_TEXT VARCHAR(255),
    TIMESTAMP_COLUMN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);